### ISSUE TITLE
Timezone is not propagated to child docker containers

### ISSUE THREAD

**Issue by mikea** [TheAppgineer/roon-extension-manager#4]
I have roon-extension-manager running in container with TZ specified:

```
$ docker inspect roon-extension-manager | grep TZ
                "TZ=America/Los_Angeles",
```

However the alarm clock extension that was installed by the manager doesn't have TZ propagated:

```
$ docker inspect roon-extension-alarm-clock | grep TZ
```

Woke me up in the middle of the night :)

**Comment by JanKoudijs** [comment]
Oops.

When the Alarm clock is installed via the Extension Manager container it allows you to set the timezone in the Docker Install Options. Set the timezone and then select the Install action. In order to do this you have to uninstall the Alarm Clock first.

I hope that this gets you woken-up at the right time.

![TZ-setup](https://user-images.githubusercontent.com/26183008/81709600-456a5300-9472-11ea-975f-b47a032f915e.png)

**Comment by mikea** [comment]
Seems to work, thanks a lot. Now I need to send couple fixes out to the alarm clock...

Best regards,
Mike
________________________________
